In [2]:
from collections import Counter

x = {'both1':1, 'both2':2, 'only_x': 100 }
y = {'both1':10, 'both2': 20, 'only_x':200 }

z = dict(Counter(x)+Counter(y))

In [3]:
Counter(x)

Counter({'both1': 1, 'both2': 2, 'only_x': 100})

In [4]:
for (k1, v1), (k2, v2) in zip(x.items(), y.items()):
    print(k1, '->', v1)
    print(k2, '->', v2)

both1 -> 1
both1 -> 10
both2 -> 2
both2 -> 20
only_x -> 100
only_x -> 200


In [5]:
x.values()

dict_values([1, 2, 100])

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [7]:
class ConvNet(nn.Module):
    """Small ConvNet for MNIST."""

    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 3, kernel_size=3)
        self.fc = nn.Linear(192, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 3))
        x = x.view(-1, 192)
        x = self.fc(x)
        return F.log_softmax(x, dim=1)

    def get_weights(self):
        return {k: v.cpu() for k, v in self.state_dict().items()}

    def set_weights(self, weights):
        self.load_state_dict(weights)

    def get_gradients(self):
        grads = []
        for p in self.parameters():
            grad = None if p.grad is None else p.grad.data.cpu().numpy()
            grads.append(grad)
        return grads

    def set_gradients(self, gradients):
        for g, p in zip(gradients, self.parameters()):
            if g is not None:
                p.grad = torch.from_numpy(g)

In [8]:
model = ConvNet()
weights = model.get_weights()

In [9]:
weights

{'conv1.weight': tensor([[[[ 0.0697,  0.2799, -0.2646],
           [ 0.1857, -0.3046,  0.1862],
           [-0.1919, -0.0227, -0.0671]]],
 
 
         [[[-0.1784, -0.2828, -0.1368],
           [ 0.0521,  0.1293,  0.3012],
           [ 0.0804, -0.0637, -0.3305]]],
 
 
         [[[-0.2956, -0.2154, -0.2274],
           [-0.1900,  0.0564,  0.0661],
           [ 0.1543,  0.1837,  0.0622]]]]),
 'conv1.bias': tensor([-0.1467,  0.2933, -0.1030]),
 'fc.weight': tensor([[-0.0556,  0.0295, -0.0216,  ...,  0.0303, -0.0256,  0.0570],
         [-0.0013, -0.0629,  0.0101,  ...,  0.0717,  0.0666,  0.0314],
         [ 0.0526, -0.0664,  0.0565,  ..., -0.0065,  0.0113,  0.0228],
         ...,
         [-0.0384,  0.0517, -0.0336,  ...,  0.0551, -0.0412,  0.0564],
         [-0.0365, -0.0295,  0.0581,  ..., -0.0689,  0.0439,  0.0636],
         [ 0.0562, -0.0415, -0.0047,  ...,  0.0498,  0.0077, -0.0588]]),
 'fc.bias': tensor([-4.7376e-02,  9.0204e-05,  5.1307e-04,  1.9474e-02, -5.4267e-02,
          4.5011

In [8]:
model_2 = ConvNet()
weights_2 = model_2.get_weights()

In [40]:
avg_weights=[
    np.stack(weight_zip).mean(axis=0) for weight_zip in zip(weights.values(), weights.values(),weights_2.values())
]

In [42]:
weights.values() + weights_2.values()


TypeError: unsupported operand type(s) for +: 'dict_values' and 'dict_values'

In [36]:
for (a, b) in zip(weights, weights_2):
    print(a)


conv1.weight
conv1.bias
fc.weight
fc.bias


In [13]:
weights_list = list(weights.values())
weights_list_2 = list(weights.values())


In [15]:
weights_list

[tensor([[[[ 0.1122, -0.1233,  0.1355],
           [ 0.1686,  0.1379, -0.2877],
           [-0.1471, -0.0436,  0.3233]]],
 
 
         [[[ 0.0156, -0.0496,  0.0201],
           [ 0.1714,  0.1244,  0.1261],
           [-0.1119, -0.2642, -0.0660]]],
 
 
         [[[-0.2263, -0.3256,  0.1658],
           [ 0.2643, -0.1028, -0.1537],
           [-0.1774, -0.0497, -0.1669]]]]),
 tensor([-0.3119,  0.2038,  0.2731]),
 tensor([[-0.0557,  0.0502, -0.0681,  ...,  0.0500, -0.0609,  0.0313],
         [-0.0537,  0.0382, -0.0603,  ..., -0.0465, -0.0625,  0.0523],
         [ 0.0140,  0.0518, -0.0251,  ...,  0.0554, -0.0198,  0.0637],
         ...,
         [ 0.0088, -0.0371,  0.0335,  ...,  0.0271, -0.0005,  0.0646],
         [ 0.0378, -0.0438,  0.0226,  ..., -0.0550, -0.0037,  0.0691],
         [-0.0315, -0.0530, -0.0689,  ..., -0.0363,  0.0314,  0.0673]]),
 tensor([-0.0283, -0.0249, -0.0285,  0.0053,  0.0152,  0.0356, -0.0320,  0.0300,
          0.0030,  0.0284])]

In [18]:
[x + y for x, y in zip(weights_list, weights_list_2)]

[tensor([[[[ 0.2244, -0.2465,  0.2710],
           [ 0.3372,  0.2758, -0.5754],
           [-0.2941, -0.0872,  0.6466]]],
 
 
         [[[ 0.0313, -0.0992,  0.0401],
           [ 0.3428,  0.2488,  0.2522],
           [-0.2238, -0.5283, -0.1321]]],
 
 
         [[[-0.4526, -0.6511,  0.3316],
           [ 0.5286, -0.2056, -0.3075],
           [-0.3548, -0.0994, -0.3337]]]]),
 tensor([-0.6237,  0.4076,  0.5462]),
 tensor([[-0.1114,  0.1004, -0.1361,  ...,  0.0999, -0.1218,  0.0626],
         [-0.1074,  0.0765, -0.1205,  ..., -0.0929, -0.1250,  0.1046],
         [ 0.0279,  0.1036, -0.0502,  ...,  0.1107, -0.0395,  0.1273],
         ...,
         [ 0.0177, -0.0743,  0.0670,  ...,  0.0542, -0.0010,  0.1293],
         [ 0.0756, -0.0877,  0.0452,  ..., -0.1100, -0.0074,  0.1382],
         [-0.0630, -0.1059, -0.1379,  ..., -0.0726,  0.0628,  0.1347]]),
 tensor([-0.0565, -0.0497, -0.0570,  0.0105,  0.0303,  0.0713, -0.0641,  0.0600,
          0.0060,  0.0568])]

In [16]:
{k: weights.get(k, 0) + weights_2.get(k, 0) for k in set(weights)}

{'conv1.weight': tensor([[[[ 0.4168,  0.0786, -0.1190],
           [ 0.0263, -0.1865, -0.2876],
           [-0.4637,  0.0598,  0.6468]]],
 
 
         [[[-0.2435,  0.0211, -0.2942],
           [ 0.1066,  0.1520,  0.1650],
           [-0.1329, -0.4348, -0.1842]]],
 
 
         [[[-0.2198, -0.4177,  0.1001],
           [ 0.0080, -0.2221,  0.1665],
           [-0.0753,  0.0858,  0.0601]]]]),
 'conv1.bias': tensor([-0.4491,  0.5310,  0.4610]),
 'fc.weight': tensor([[ 0.0095, -0.0138, -0.0585,  ...,  0.1200, -0.0516,  0.0795],
         [-0.0438, -0.0075, -0.1087,  ..., -0.0917, -0.1291,  0.0614],
         [-0.0517,  0.0248,  0.0452,  ...,  0.0042,  0.0377,  0.0359],
         ...,
         [-0.0167,  0.0139, -0.0207,  ..., -0.0304, -0.0037,  0.0665],
         [ 0.0492, -0.0658,  0.0847,  ..., -0.0663, -0.0737,  0.0533],
         [ 0.0223, -0.0585, -0.0406,  ...,  0.0106,  0.0867,  0.0306]]),
 'fc.bias': tensor([-0.0791, -0.0605, -0.0802,  0.0547,  0.0185,  0.1013, -0.0881,  0.0934,
         

In [4]:
import heapq
x = [2,1,3]
heapq.heapify(x)
# heapq.heappop(x)

In [5]:
x

[1, 2, 3]

In [6]:
min([])

ValueError: min() arg is an empty sequence

In [8]:
x = [2,3,3,5]
heapq.heapify(x)

In [9]:
x.remove(3)

In [10]:
x

[2, 3, 5]